"""nex_task_id previous_task_id right_answer student_answer add in InProgressTasks

Revision ID: fa93eca237f0
Revises: 05ef3f589b55
Create Date: 2024-06-05 18:18:24.485116

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fa93eca237f0"
down_revision: Union[str, None] = "05ef3f589b55"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "in_progress_tasks",
        sa.Column("nex_task_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "in_progress_tasks",
        sa.Column("previous_task_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "in_progress_tasks",
        sa.Column("right_answer", sa.Boolean(), nullable=False),
    )
    op.add_column(
        "in_progress_tasks",
        sa.Column("student_answer", sa.Boolean(), nullable=True),
    )
    op.alter_column(
        "in_progress_tasks",
        "answer",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    op.create_foreign_key(
        None,
        "in_progress_tasks",
        "task_types",
        ["previous_task_id"],
        ["id"],
        ondelete="set null",
    )
    op.create_foreign_key(
        None,
        "in_progress_tasks",
        "task_types",
        ["nex_task_id"],
        ["id"],
        ondelete="set null",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "in_progress_tasks", type_="foreignkey")
    op.drop_constraint(None, "in_progress_tasks", type_="foreignkey")
    op.alter_column(
        "in_progress_tasks",
        "answer",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.drop_column("in_progress_tasks", "student_answer")
    op.drop_column("in_progress_tasks", "right_answer")
    op.drop_column("in_progress_tasks", "previous_task_id")
    op.drop_column("in_progress_tasks", "nex_task_id")
    # ### end Alembic commands ###
