"""point nuleble true in in_progress_lessons

Revision ID: da09289e4eb4
Revises: 0ff24b6c9763
Create Date: 2024-06-15 19:44:25.699487

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "da09289e4eb4"
down_revision: Union[str, None] = "0ff24b6c9763"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "in_progress_lessons",
        "point",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "in_progress_lessons",
        "point",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###
