"""rename text > question in tasks and completed_tasks

Revision ID: 8e8e521c8ab6
Revises: 994f99b60ce9
Create Date: 2024-05-31 15:04:08.834391

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8e8e521c8ab6"
down_revision: Union[str, None] = "994f99b60ce9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "completed_tasks", sa.Column("question", sa.TEXT(), nullable=False)
    )
    op.drop_column("completed_tasks", "text")
    op.add_column("tasks", sa.Column("question", sa.TEXT(), nullable=False))
    op.drop_column("tasks", "text")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column("text", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_column("tasks", "question")
    op.add_column(
        "completed_tasks",
        sa.Column("text", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_column("completed_tasks", "question")
    # ### end Alembic commands ###
