"""delete tg_id in users

Revision ID: e1e601defa1c
Revises: de97f059c9fb
Create Date: 2024-05-30 19:38:08.311476

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e1e601defa1c"
down_revision: Union[str, None] = "de97f059c9fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_tg_id_key", "users", type_="unique")
    op.drop_column("users", "tg_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "tg_id",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_unique_constraint("users_tg_id_key", "users", ["tg_id"])
    # ### end Alembic commands ###
