"""add created_at, updated_at all models

Revision ID: 527b10554ff6
Revises: f672beb548fa
Create Date: 2024-05-31 10:45:41.012252

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "527b10554ff6"
down_revision: Union[str, None] = "f672beb548fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lessons", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "lessons", sa.Column("updated_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "profiles_student",
        sa.Column("created_at", sa.DateTime(), nullable=False),
    )
    op.add_column(
        "profiles_student",
        sa.Column("updated_at", sa.DateTime(), nullable=False),
    )
    op.add_column(
        "profiles_teacher",
        sa.Column("created_at", sa.DateTime(), nullable=False),
    )
    op.add_column(
        "profiles_teacher",
        sa.Column("updated_at", sa.DateTime(), nullable=False),
    )
    op.add_column(
        "users", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "users", sa.Column("updated_at", sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "updated_at")
    op.drop_column("users", "created_at")
    op.drop_column("profiles_teacher", "updated_at")
    op.drop_column("profiles_teacher", "created_at")
    op.drop_column("profiles_student", "updated_at")
    op.drop_column("profiles_student", "created_at")
    op.drop_column("lessons", "updated_at")
    op.drop_column("lessons", "created_at")
    # ### end Alembic commands ###
