"""fix field name nex_task_id to next_task_id in_progress_tasks table

Revision ID: afcbe192c971
Revises: 40877c73e028
Create Date: 2024-06-16 18:44:39.018265

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "afcbe192c971"
down_revision: Union[str, None] = "40877c73e028"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "in_progress_tasks",
        sa.Column("next_task_id", sa.Integer(), nullable=True),
    )
    op.drop_column("in_progress_tasks", "nex_task_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "in_progress_tasks",
        sa.Column(
            "nex_task_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("in_progress_tasks", "next_task_id")
    # ### end Alembic commands ###
