"""add bio, image field in profiles_teacher

Revision ID: ee009a465ae2
Revises: 8e8e521c8ab6
Create Date: 2024-05-31 15:08:30.658433

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ee009a465ae2"
down_revision: Union[str, None] = "8e8e521c8ab6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles_teacher",
        sa.Column("bio", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "profiles_teacher",
        sa.Column("image", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profiles_teacher", "image")
    op.drop_column("profiles_teacher", "bio")
    # ### end Alembic commands ###
