"""link in_progress_lessons table to lessons table

Revision ID: d62e3a84e7cb
Revises: 95fe250db3d0
Create Date: 2024-06-24 16:13:44.619002

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d62e3a84e7cb"
down_revision: Union[str, None] = "95fe250db3d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "in_progress_lessons",
        sa.Column("parent_lesson_id", sa.Integer(), nullable=False),
    )
    op.create_foreign_key(
        None, "in_progress_lessons", "lessons", ["parent_lesson_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "in_progress_lessons", type_="foreignkey")
    op.drop_column("in_progress_lessons", "parent_lesson_id")
    # ### end Alembic commands ###
