"""add img in in_progress_tasks table

Revision ID: b5796f1b0bd8
Revises: da09289e4eb4
Create Date: 2024-06-15 19:48:57.715085

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b5796f1b0bd8"
down_revision: Union[str, None] = "da09289e4eb4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "in_progress_tasks", sa.Column("img", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("in_progress_tasks", "img")
    # ### end Alembic commands ###
