"""fix fk task to lesson

Revision ID: 9a4075c2fd36
Revises: afcbe192c971
Create Date: 2024-06-19 20:53:12.879123

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9a4075c2fd36"
down_revision: Union[str, None] = "afcbe192c971"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tasks_lesson_id_fkey", "tasks", type_="foreignkey")
    op.create_foreign_key(
        None, "tasks", "lessons", ["lesson_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.create_foreign_key(
        "tasks_lesson_id_fkey", "tasks", "lessons", ["lesson_id"], ["id"]
    )
    # ### end Alembic commands ###
