"""add img field in Tasks

Revision ID: b7537b297bce
Revises: fc43576dc878
Create Date: 2024-06-08 11:10:43.131102

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b7537b297bce"
down_revision: Union[str, None] = "fc43576dc878"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("img", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "img")
    # ### end Alembic commands ###
