"""added tg_id in users

Revision ID: f672beb548fa
Revises: e1e601defa1c
Create Date: 2024-05-30 19:38:37.824841

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f672beb548fa"
down_revision: Union[str, None] = "e1e601defa1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("tg_id", sa.Integer(), nullable=False))
    op.create_unique_constraint(None, "users", ["tg_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "tg_id")
    # ### end Alembic commands ###
