"""renamed tabel completed_lessons to in_progress_lessons

Revision ID: 4a91cd7a981c
Revises: c07617185221
Create Date: 2024-06-15 18:50:07.306963

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a91cd7a981c"
down_revision: Union[str, None] = "c07617185221"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "in_progress_lessons",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("point", sa.Integer(), nullable=False),
        sa.Column("teacher_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["profiles_student.id"],
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["profiles_teacher.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.add_column(
        "in_progress_tasks",
        sa.Column("in_progress_lessons_id", sa.Integer(), nullable=False),
    )
    op.create_foreign_key(
        None,
        "in_progress_tasks",
        "in_progress_lessons",
        ["in_progress_lessons_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "in_progress_tasks", type_="foreignkey")
    op.drop_column("in_progress_tasks", "in_progress_lessons_id")
    op.drop_table("in_progress_lessons")
    # ### end Alembic commands ###
