"""added fk from user to profiles teacher table

Revision ID: 959457e5c780
Revises: db4a835b972a
Create Date: 2024-05-28 11:48:44.918808

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "959457e5c780"
down_revision: Union[str, None] = "db4a835b972a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles_teacher", sa.Column("user_id", sa.Integer(), nullable=False)
    )
    op.create_unique_constraint(None, "profiles_teacher", ["user_id"])
    op.create_foreign_key(
        None, "profiles_teacher", "users", ["user_id"], ["id"]
    )
    op.add_column(
        "users", sa.Column("tg_id", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "users", sa.Column("is_teacher", sa.Boolean(), nullable=False)
    )
    op.create_unique_constraint(None, "users", ["tg_id"])
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("first_name", sa.VARCHAR(length=255), nullable=True)
    )
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "is_teacher")
    op.drop_column("users", "tg_id")
    op.drop_constraint(None, "profiles_teacher", type_="foreignkey")
    op.drop_constraint(None, "profiles_teacher", type_="unique")
    op.drop_column("profiles_teacher", "user_id")
    # ### end Alembic commands ###
