"""fix fk nex_task_id previous_task_id

Revision ID: 46168f8bf527
Revises: fa93eca237f0
Create Date: 2024-06-05 18:22:04.267416

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "46168f8bf527"
down_revision: Union[str, None] = "fa93eca237f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "in_progress_tasks_previous_task_id_fkey",
        "in_progress_tasks",
        type_="foreignkey",
    )
    op.drop_constraint(
        "in_progress_tasks_nex_task_id_fkey",
        "in_progress_tasks",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "in_progress_tasks",
        "in_progress_tasks",
        ["previous_task_id"],
        ["id"],
        ondelete="set null",
    )
    op.create_foreign_key(
        None,
        "in_progress_tasks",
        "in_progress_tasks",
        ["nex_task_id"],
        ["id"],
        ondelete="set null",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "in_progress_tasks", type_="foreignkey")
    op.drop_constraint(None, "in_progress_tasks", type_="foreignkey")
    op.create_foreign_key(
        "in_progress_tasks_nex_task_id_fkey",
        "in_progress_tasks",
        "task_types",
        ["nex_task_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "in_progress_tasks_previous_task_id_fkey",
        "in_progress_tasks",
        "task_types",
        ["previous_task_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
