"""add fk tasks to lessons

Revision ID: 346f2e6cf390
Revises: 538bfed752dc
Create Date: 2024-05-31 11:09:39.126739

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "346f2e6cf390"
down_revision: Union[str, None] = "538bfed752dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("lesson_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "tasks", "lessons", ["lesson_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_column("tasks", "lesson_id")
    # ### end Alembic commands ###
