"""delete fk student in in_progress_tasks

Revision ID: 05ef3f589b55
Revises: 64412e1ca034
Create Date: 2024-06-05 18:17:49.792791

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "05ef3f589b55"
down_revision: Union[str, None] = "64412e1ca034"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "in_progress_tasks_student_id_fkey",
        "in_progress_tasks",
        type_="foreignkey",
    )
    op.drop_column("in_progress_tasks", "student_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "in_progress_tasks",
        sa.Column(
            "student_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "in_progress_tasks_student_id_fkey",
        "in_progress_tasks",
        "profiles_student",
        ["student_id"],
        ["id"],
    )
    # ### end Alembic commands ###
