"""add progress field to in_progress_tasks table

Revision ID: 40877c73e028
Revises: 9637e8883988
Create Date: 2024-06-16 14:30:32.335680

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "40877c73e028"
down_revision: Union[str, None] = "9637e8883988"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    progress_enum = sa.Enum("incomplete", "now", "complete", name="progress")
    progress_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "in_progress_tasks",
        sa.Column(
            "progress",
            progress_enum,
            server_default="incomplete",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the column first
    op.drop_column("in_progress_tasks", "progress")

    # Drop the enum type
    progress_enum = sa.Enum("incomplete", "now", "complete", name="progress")
    progress_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
