"""fix fk task to lesson

Revision ID: 94b68b51649d
Revises: 9a4075c2fd36
Create Date: 2024-06-19 21:24:35.635731

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "94b68b51649d"
down_revision: Union[str, None] = "9a4075c2fd36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks", "lesson_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks", "lesson_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
