"""delete completed_lesson_id in in_progress_tasks table

Revision ID: 2a463bbf86a2
Revises: 344aeb9a31a7
Create Date: 2024-06-15 18:48:54.171102

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2a463bbf86a2"
down_revision: Union[str, None] = "344aeb9a31a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "in_progress_tasks_completed_lesson_id_fkey",
        "in_progress_tasks",
        type_="foreignkey",
    )
    op.drop_column("in_progress_tasks", "completed_lesson_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "in_progress_tasks",
        sa.Column(
            "completed_lesson_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_foreign_key(
        "in_progress_tasks_completed_lesson_id_fkey",
        "in_progress_tasks",
        "completed_lessons",
        ["completed_lesson_id"],
        ["id"],
    )
    # ### end Alembic commands ###
