"""added fk from user to profiles student table

Revision ID: d2cb2d1d6349
Revises: 54c487a3f5fa
Create Date: 2024-05-28 12:11:35.554150

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d2cb2d1d6349"
down_revision: Union[str, None] = "54c487a3f5fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("is_student", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_student")
    # ### end Alembic commands ###
