"""fixed nex_task_id, previous_task_id in in_progress_tasks

Revision ID: da50845f1fdd
Revises: b5796f1b0bd8
Create Date: 2024-06-15 20:04:43.965756

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "da50845f1fdd"
down_revision: Union[str, None] = "b5796f1b0bd8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "in_progress_tasks_previous_task_id_fkey",
        "in_progress_tasks",
        type_="foreignkey",
    )
    op.drop_constraint(
        "in_progress_tasks_nex_task_id_fkey",
        "in_progress_tasks",
        type_="foreignkey",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "in_progress_tasks_nex_task_id_fkey",
        "in_progress_tasks",
        "in_progress_tasks",
        ["nex_task_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "in_progress_tasks_previous_task_id_fkey",
        "in_progress_tasks",
        "in_progress_tasks",
        ["previous_task_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
